# https://stackoverflow.com/questions/23793062/can-forks-be-synced-automatically-in-github

name: Merge upstream branches
on:
  schedule:
     # each sunday
    - cron:  '*/3 * * * *' # each sunday '0 1 * * 0'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'albertmena'
          git config --global user.email 'alber.mena@gmail.com'

          git pull --unshallow  

          git remote add cell https://github.com/albertmena/cellModel
          git fetch cell

          git checkout -b cell_refresh master/contaminacionMAdrid/cellModel-master
          git merge --no-edit cell
          git push origin cell_refresh

          git checkout master
          git merge --no-edit cell_refresh  #o cell no estoy seguro
          git push origin master

      
